# Generated by Django 3.1.7 on 2021-03-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebook',
            name='Image',
            field=models.ImageField(upload_to='Imagebook'),
        ),
    ]
