# Generated by Django 3.1.7 on 2021-03-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210313_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebook',
            name='Image',
            field=models.CharField(max_length=1000000),
        ),
    ]
